//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifewareSoftwareLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifewareSoftwareLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de autenticación.
        /// </summary>
        public static string AuthenticationErrorTitle {
            get {
                return ResourceManager.GetString("AuthenticationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando validez de datos de licencia.
        /// </summary>
        public static string CheckingSerialMessage {
            get {
                return ResourceManager.GetString("CheckingSerialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando Serial.
        /// </summary>
        public static string CheckingSerialTitle {
            get {
                return ResourceManager.GetString("CheckingSerialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial no válida..
        /// </summary>
        public static string CheckSerialErrorDetail {
            get {
                return ResourceManager.GetString("CheckSerialErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del error.
        /// </summary>
        public static string ErrorDetail {
            get {
                return ResourceManager.GetString("ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Por favor reintente..
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string HintPassword {
            get {
                return ResourceManager.GetString("HintPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string HintUser {
            get {
                return ResourceManager.GetString("HintUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicializando el cargador del sistema..
        /// </summary>
        public static string IntroMessage {
            get {
                return ResourceManager.GetString("IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a {0}.
        /// </summary>
        public static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar {0}.
        /// </summary>
        public static string LaunchErrorDetail {
            get {
                return ResourceManager.GetString("LaunchErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sistema se iniciará en unos segundos.
        /// </summary>
        public static string LaunchMessage {
            get {
                return ResourceManager.GetString("LaunchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando {0}.
        /// </summary>
        public static string LaunchTitle {
            get {
                return ResourceManager.GetString("LaunchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para continuar, por favor ingrese los datos solicitados..
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Launcher.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta operación puede tardar unos segundos. Aparecerán diálogos, solicitando sus permisos..
        /// </summary>
        public static string RegisterKeyboardMessage {
            get {
                return ResourceManager.GetString("RegisterKeyboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrando teclado.
        /// </summary>
        public static string RegisterKeyboardTitle {
            get {
                return ResourceManager.GetString("RegisterKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de serial.
        /// </summary>
        public static string SerialErrorTitle {
            get {
                return ResourceManager.GetString("SerialErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicializar {0}.
        /// </summary>
        public static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere mientras se registran los datos de serial..
        /// </summary>
        public static string ValidatingSerialMessage {
            get {
                return ResourceManager.GetString("ValidatingSerialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrando serial..
        /// </summary>
        public static string ValidatingSerialTitle {
            get {
                return ResourceManager.GetString("ValidatingSerialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo conectar al servidor. Por favor reintente..
        /// </summary>
        public static string ValidationConnectionError {
            get {
                return ResourceManager.GetString("ValidationConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos provistos son incorrectos. Por favor reintente..
        /// </summary>
        public static string ValidationIncorrectDataError {
            get {
                return ResourceManager.GetString("ValidationIncorrectDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El serial asignado a su cuenta no está habilitado..
        /// </summary>
        public static string ValidationSerialDisabled {
            get {
                return ResourceManager.GetString("ValidationSerialDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay seriales asignados a su cuenta..
        /// </summary>
        public static string ValidationSerialNotAssigned {
            get {
                return ResourceManager.GetString("ValidationSerialNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El serial asignado a su cuenta ha sobrepasado el límite de uso..
        /// </summary>
        public static string ValidationSerialUsageExceeded {
            get {
                return ResourceManager.GetString("ValidationSerialUsageExceeded", resourceCulture);
            }
        }
    }
}
